// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/blackdark/pulumi-netcup/sdk/go/pulumi-netcup/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The Netcup API key for authentication
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "netcup:apiKey")
}

// The Netcup API password for authentication
func GetApiPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "netcup:apiPassword")
}

// The Netcup customer ID
func GetCustomerId(ctx *pulumi.Context) string {
	return config.Get(ctx, "netcup:customerId")
}
