version: "2"
linters:
  enable:
    - copyloopvar
    - depguard
    - exhaustive
    - gocritic
    - goheader
    - gosec
    - importas
    - lll
    - misspell
    - nakedret
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - unconvert
  settings:
    depguard:
      rules:
        protobuf:
          deny:
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - importShadow
    goheader:
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
    nakedret:
      max-func-lines: 60
    nolintlint:
      allow-unused: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
      - linters:
          - revive
        text: 'empty-block: this block is empty, you can remove it'
      - linters:
          - revive
        text: 'redefines-builtin-id: redefinition of the built-in function new'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - blank
        - default
        - prefix(github.com/pulumi/)
        - prefix(github.com/pulumi/pulumi-dockerbuild/)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
