// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Blackdark.Netcup
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("netcup");

        private static readonly __Value<string?> _apiKey = new __Value<string?>(() => __config.Get("apiKey"));
        /// <summary>
        /// The Netcup API key for authentication
        /// </summary>
        public static string? ApiKey
        {
            get => _apiKey.Get();
            set => _apiKey.Set(value);
        }

        private static readonly __Value<string?> _apiPassword = new __Value<string?>(() => __config.Get("apiPassword"));
        /// <summary>
        /// The Netcup API password for authentication
        /// </summary>
        public static string? ApiPassword
        {
            get => _apiPassword.Get();
            set => _apiPassword.Set(value);
        }

        private static readonly __Value<string?> _customerId = new __Value<string?>(() => __config.Get("customerId"));
        /// <summary>
        /// The Netcup customer ID
        /// </summary>
        public static string? CustomerId
        {
            get => _customerId.Get();
            set => _customerId.Set(value);
        }

    }
}
