// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.blackdark.netcup;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * The Netcup API key for authentication
     * 
     */
    @Import(name="apiKey", required=true)
    private Output<String> apiKey;

    /**
     * @return The Netcup API key for authentication
     * 
     */
    public Output<String> apiKey() {
        return this.apiKey;
    }

    /**
     * The Netcup API password for authentication
     * 
     */
    @Import(name="apiPassword", required=true)
    private Output<String> apiPassword;

    /**
     * @return The Netcup API password for authentication
     * 
     */
    public Output<String> apiPassword() {
        return this.apiPassword;
    }

    /**
     * The Netcup customer ID
     * 
     */
    @Import(name="customerId", required=true)
    private Output<String> customerId;

    /**
     * @return The Netcup customer ID
     * 
     */
    public Output<String> customerId() {
        return this.customerId;
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.apiKey = $.apiKey;
        this.apiPassword = $.apiPassword;
        this.customerId = $.customerId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiKey The Netcup API key for authentication
         * 
         * @return builder
         * 
         */
        public Builder apiKey(Output<String> apiKey) {
            $.apiKey = apiKey;
            return this;
        }

        /**
         * @param apiKey The Netcup API key for authentication
         * 
         * @return builder
         * 
         */
        public Builder apiKey(String apiKey) {
            return apiKey(Output.of(apiKey));
        }

        /**
         * @param apiPassword The Netcup API password for authentication
         * 
         * @return builder
         * 
         */
        public Builder apiPassword(Output<String> apiPassword) {
            $.apiPassword = apiPassword;
            return this;
        }

        /**
         * @param apiPassword The Netcup API password for authentication
         * 
         * @return builder
         * 
         */
        public Builder apiPassword(String apiPassword) {
            return apiPassword(Output.of(apiPassword));
        }

        /**
         * @param customerId The Netcup customer ID
         * 
         * @return builder
         * 
         */
        public Builder customerId(Output<String> customerId) {
            $.customerId = customerId;
            return this;
        }

        /**
         * @param customerId The Netcup customer ID
         * 
         * @return builder
         * 
         */
        public Builder customerId(String customerId) {
            return customerId(Output.of(customerId));
        }

        public ProviderArgs build() {
            if ($.apiKey == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "apiKey");
            }
            if ($.apiPassword == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "apiPassword");
            }
            if ($.customerId == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "customerId");
            }
            return $;
        }
    }

}
