// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("netcup");

/**
 * The Netcup API key for authentication
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey");
    },
    enumerable: true,
});

/**
 * The Netcup API password for authentication
 */
export declare const apiPassword: string | undefined;
Object.defineProperty(exports, "apiPassword", {
    get() {
        return __config.get("apiPassword");
    },
    enumerable: true,
});

/**
 * The Netcup customer ID
 */
export declare const customerId: string | undefined;
Object.defineProperty(exports, "customerId", {
    get() {
        return __config.get("customerId");
    },
    enumerable: true,
});

