// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package puluminetcup

import (
	"context"
	"reflect"

	"errors"
	"github.com/blackdark/pulumi-netcup/sdk/go/pulumi-netcup/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// The Netcup API key for authentication
	ApiKey pulumi.StringOutput `pulumi:"apiKey"`
	// The Netcup API password for authentication
	ApiPassword pulumi.StringOutput `pulumi:"apiPassword"`
	// The Netcup customer ID
	CustomerId pulumi.StringOutput `pulumi:"customerId"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiKey == nil {
		return nil, errors.New("invalid value for required argument 'ApiKey'")
	}
	if args.ApiPassword == nil {
		return nil, errors.New("invalid value for required argument 'ApiPassword'")
	}
	if args.CustomerId == nil {
		return nil, errors.New("invalid value for required argument 'CustomerId'")
	}
	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringInput)
	}
	if args.ApiPassword != nil {
		args.ApiPassword = pulumi.ToSecret(args.ApiPassword).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
		"apiPassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:netcup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The Netcup API key for authentication
	ApiKey string `pulumi:"apiKey"`
	// The Netcup API password for authentication
	ApiPassword string `pulumi:"apiPassword"`
	// The Netcup customer ID
	CustomerId string `pulumi:"customerId"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The Netcup API key for authentication
	ApiKey pulumi.StringInput
	// The Netcup API password for authentication
	ApiPassword pulumi.StringInput
	// The Netcup customer ID
	CustomerId pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The Netcup API key for authentication
func (o ProviderOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ApiKey }).(pulumi.StringOutput)
}

// The Netcup API password for authentication
func (o ProviderOutput) ApiPassword() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ApiPassword }).(pulumi.StringOutput)
}

// The Netcup customer ID
func (o ProviderOutput) CustomerId() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.CustomerId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
