// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netcup.netcup;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("netcup");
/**
 * The Netcup API key for authentication
 * 
 */
    public String apiKey() {
        return Codegen.stringProp("apiKey").config(config).require();
    }
/**
 * The Netcup API password for authentication
 * 
 */
    public String apiPassword() {
        return Codegen.stringProp("apiPassword").config(config).require();
    }
/**
 * The Netcup customer ID
 * 
 */
    public String customerId() {
        return Codegen.stringProp("customerId").config(config).require();
    }
}
