// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netcup.netcup;

import com.netcup.netcup.DnsRecordArgs;
import com.netcup.netcup.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A DNS record managed by Netcup DNS service
 * 
 */
@ResourceType(type="netcup:index:DnsRecord")
public class DnsRecord extends com.pulumi.resources.CustomResource {
    /**
     * The domain name for the DNS record
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    /**
     * @return The domain name for the DNS record
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }
    /**
     * The fully qualified domain name
     * 
     */
    @Export(name="fqdn", refs={String.class}, tree="[0]")
    private Output<String> fqdn;

    /**
     * @return The fully qualified domain name
     * 
     */
    public Output<String> fqdn() {
        return this.fqdn;
    }
    /**
     * The hostname for the DNS record
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The hostname for the DNS record
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The priority for the DNS record
     * 
     */
    @Export(name="priority", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> priority;

    /**
     * @return The priority for the DNS record
     * 
     */
    public Output<Optional<String>> priority() {
        return Codegen.optional(this.priority);
    }
    /**
     * The unique identifier for the DNS record
     * 
     */
    @Export(name="recordId", refs={String.class}, tree="[0]")
    private Output<String> recordId;

    /**
     * @return The unique identifier for the DNS record
     * 
     */
    public Output<String> recordId() {
        return this.recordId;
    }
    /**
     * The DNS record type
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return The DNS record type
     * 
     */
    public Output<String> type() {
        return this.type;
    }
    /**
     * The value/destination for the DNS record
     * 
     */
    @Export(name="value", refs={String.class}, tree="[0]")
    private Output<String> value;

    /**
     * @return The value/destination for the DNS record
     * 
     */
    public Output<String> value() {
        return this.value;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DnsRecord(java.lang.String name) {
        this(name, DnsRecordArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DnsRecord(java.lang.String name, DnsRecordArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DnsRecord(java.lang.String name, DnsRecordArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netcup:index:DnsRecord", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DnsRecord(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netcup:index:DnsRecord", name, null, makeResourceOptions(options, id), false);
    }

    private static DnsRecordArgs makeArgs(DnsRecordArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DnsRecordArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DnsRecord get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DnsRecord(name, id, options);
    }
}
