// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netcup.netcup;

import com.netcup.netcup.ProviderArgs;
import com.netcup.netcup.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="pulumi:providers:netcup")
public class Provider extends com.pulumi.resources.ProviderResource {
    /**
     * The Netcup API key for authentication
     * 
     */
    @Export(name="apiKey", refs={String.class}, tree="[0]")
    private Output<String> apiKey;

    /**
     * @return The Netcup API key for authentication
     * 
     */
    public Output<String> apiKey() {
        return this.apiKey;
    }
    /**
     * The Netcup API password for authentication
     * 
     */
    @Export(name="apiPassword", refs={String.class}, tree="[0]")
    private Output<String> apiPassword;

    /**
     * @return The Netcup API password for authentication
     * 
     */
    public Output<String> apiPassword() {
        return this.apiPassword;
    }
    /**
     * The Netcup customer ID
     * 
     */
    @Export(name="customerId", refs={String.class}, tree="[0]")
    private Output<String> customerId;

    /**
     * @return The Netcup customer ID
     * 
     */
    public Output<String> customerId() {
        return this.customerId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Provider(java.lang.String name) {
        this(name, ProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Provider(java.lang.String name, ProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Provider(java.lang.String name, ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netcup", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private static ProviderArgs makeArgs(ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProviderArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "apiKey",
                "apiPassword"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

}
